import React from 'react';
import { FunctionComponent } from 'react';
import { Modal } from 'antd';

export interface IGdprContentModalProps {
    modalVisible: boolean;
    setModalVisible: (visible: boolean) => void;

}

const GdprContentModal: FunctionComponent<IGdprContentModalProps> = (props) => {

    const DisplayRegulations = () => {
        /*const rodo = "KLAUZULA INFORMACYJNA – ZGODA NA PRZETWARZANIE DANYCH\n\nZgodnie z art. 13 ust. 1 i 2 rozporządzenia Parlamentu Europejskiego I Rady (UE) 2016/679 z dnia 27 kwietnia 2016 r. w sprawie ochrony osób fizycznych w związku z przetwarzaniem danych osobowych i w sprawie swobodnego przepływu takich danych oraz uchylenia dyrektywy 95/46/WE (ogólne rozporządzenie o ochronie danych), (Dz. U. UE. L Nr 119, str. 1) – dalej „RODO” informuję, iż:\nKlient który przekazał nam swoje dane osobowe ma prawo dostępu do tych danych oraz prawo:\nINFORMACJA O PRAWIE SPRZECIWU\nJeśli Pani/Pana dane osobowe są przetwarzane dla celów marketingu bezpośredniego ma Pani/Pan prawo wnieść w dowolnym momencie, bezpłatnie sprzeciw wobec tego przetwarzania pierwotnego lub dalszego – w tym profilowania, o ile jest ono powiązane z marketingiem bezpośrednim.\nAdministratorem Pani/Pana danych osobowych jest WAR ZONE S.C., ul. Kolbuszowska 25/1, 53-404 Wrocław\nWe wszystkich sprawach dotyczących przetwarzania danych osobowych przez Administratora oraz korzystania z praw związanych z przetwarzaniem danych osobowych można kontaktować się na adres" +
        +" e-mail: biuro@war-zone.com.pl, lub pisemnie na wyżej podany adres Administratora z dopiskiem „dane osobowe”.\n§1. Pani/Pana dane osobowe będą przez nas przetwarzane w celu dla którego udzielona została zgoda i może być to:\nrealizacja rezerwacji na strzelnicę / laser tag\nPrzetwarzanie w powyższym zakresie odbywa się na podstawie udzielonej zgody (art. 6 ust. 1 pkt a) RODO), ponadto przekazane dane osobowe mogą być przetwarzane:\newentualnie w celu marketingu bezpośredniego produktów i usług własnych Administratora, przetwarzanie odbywa się na podstawie tzw. prawnie uzasadnionego interesu Administratora jakim jest prowadzenie marketingu bezpośredniego swoich usług i produktów (art. 6 ust. 1 pkt. f) RODO),\nświadczenia usług przewidzianych dla użytkowników kont zgodnie z Regulaminem, którego akceptacja równoznaczna jest z zawarciem umowy o świadczenie tychże usług. Przetwarzanie odbywa się w celu wykonania umowy (art. 6 ust. 1 pkt. b) RODO),\newentualnie w celu dochodzenia roszczeń związanych z zawartą umową i świadczonymi usługami. Przetwarzanie odbywa się na podstawie prawnie uzasadnionego interesu Administratora jakim "+
        +" jest możliwość dochodzenia roszczeń (art. 6 ust. 1 pkt. f) RODO),\nwykonania ciążących na Administratorze obowiązków prawnych. Przetwarzanie odbywa się na podstawie obowiązku prawnego (art. 6 ust. 1 pkt c) RODO).\n§2. Przekazane nam dane osobowe mogą być udostępnione podmiotom przetwarzającym dane na polecenie Administratora, m.inn. świadczącym usługi informatyczne, kurierskie, przetwarzania płatności, windykacji, doręczania korespondencji pocztowej, usługi prawne i inne wyspecjalizowane usługi. Takie podmioty przetwarzają dane wyłącznie na podstawie umowy z Administratorem i zgodnie z naszymi poleceniami. Udostępniamy tylko te dane osobowe, które umożliwiają wyżej wskazanym podmiotom świadczenie przez nich usług. Pani/Pana dane mogę być też udostępnione osobom trzecim w celach marketingowych jeśli wyrazi Pani/Pan zgodę na określone cele marketingowe, dla których niezbędne jest udostępnienie danych. Dane osobowe mogą być także dostępne dla dostawcy usług hostingowych, w zakresie utrzymania stron internetowych i kampanii marketingowych wyłącznie jednak w związku z działalnością statutową prowadzoną przez Administratora."
        +" W żadnym przypadku podmiot dla którego dostępne będą dane osobowe użytkowników nie stanie się jednak administratorem powierzonych nam danych osobowych.\n§3. Pani/Pana dane osobowe nie będą przekazywane do odbiorców znajdujących się w państwach poza Europejskim Obszarem Gospodarczym (kraje Unii Europejskiej oraz Islandia, Norwegia i Lichtenstein).\n§4. Pani/Pana dane osobowe będą przechowywane do momentu przedawnienia roszczeń z tytułu umowy/ świadczenia usług lub do momentu wygaśnięcia obowiązku przechowywania danych wynikającego z przepisów prawa. Tam gdzie przetwarzamy dane osobowe w oparciu o usprawiedliwiony interes Administratora dane osobowe nie będą przetwarzane do określonego celu jeśli zgłosi Pani/Pan sprzeciw wobec takiego przetwarzania. Jeśli przetwarzamy dane w oparciu o Pani/Pana zgodę, dane osobowe będą przetwarzane do momentu jej wycofania. Po upływie tego okresu dane osobowe zostaną usunięte lub poddane anonimizacji tj. zostaną przetworzone w taki sposób aby nie było możliwe powiązanie ich z żadną osobą.\n§5. Posiada Pani/Pan prawo żądania dostępu do swoich danych osobowych, otrzymania ich kopii, sprostowania"
        +" (poprawiania), usunięcia lub ograniczenia przetwarzania. wniesienia sprzeciwu wobec takiego przetwarzania. Jeśli podstawą przetwarzania danych jest prawnie uzasadniony interes Administratora, może Pani/Pan wnieść sprzeciw wobec takiego przetwarzania, w szczególności wobec przetwarzania na potrzeby marketingu bezpośredniego, w tym profilowania i w celach analitycznych. Przysługuje Pani/Panu prawo do przenoszenia danych osobowych. W takiej sytuacji otrzyma Pani/Pan swoje dane osobowe w ustrukturyzowanym, powszechnie używanym formacie, nadającym się do odczytu maszynowego.\n§6. Przysługuje Pani/Panu prawo do cofnięcia zgody w dowolnym momencie. Wycofanie zgody nie wpływa jednak na zgodność z prawem przetwarzania, którego dokonano na podstawie zgody przed jej wycofaniem. Oświadczenie o cofnięciu zgody na przetwarzanie danych osobowych należy przekazać na adres: WAR ZONE S.C, ul. Kolbuszowska 25/1, 53-404 Wrocław\n§7. Podanie danych osobowych jest dobrowolne ale konieczne do świadczenia usług objętych udzieloną zgodą – bez ich podania nie jest możliwe świadczenie usług. Podanie danych w celach marketingowych jest dobrowolne."
        +" Podanie danych osobowych w zakresie mającym podstawę w zobowiązaniu umownym, w tym przede wszystkim w zakresie świadczenia usług dla użytkowników kont jest dobrowolne, jednakże jest warunkiem zawarcia i wykonywania umowy. Konsekwencja niepodania danych będzie niemożność świadczenia usług przeznaczonych dla użytkowników kont. Podanie danych osobowych w zakresie wynikającym z przepisów prawa jest obowiązkowe i niezbędne do świadczenia przez Administratora usług/wykonania umowy.\n§8. Przysługuje Pani/Panu prawo do wniesienia skargi do Prezesa Urzędu Ochrony Danych Osobowych, gdy uzna Pani/Pan, iż przetwarzanie Pani/ Pana danych osobowych narusza przepisy o ochronie danych osobowych,\n§9. Pani/Pana dane będą przetwarzane w sposób zautomatyzowany ( w tym w formie profilowania) jednakże nie będzie to wywoływać wobec Pani/Pana żadnych skutków prawnych lub w podobny sposób istotnie wpływać na Pani/Pana sytuację. Profilowanie danych osobowych polega na przetwarzaniu Pani/Pana danych (również w sposób zautomatyzowany) poprzez wykorzystanie ich do oceny niektórych informacji, w szczególności do analizy lub prognozy osobistych preferencji oraz zainteresowań oraz przesyłania Pani/Panu ofert dotyczących zakupu towarów. Ma Pani/Pan prawo wnieść sprzeciw wobec profilowania.";
        return (
            rodo.split('\n').map(line => (
                <div>
                    {line}
                </div>
            ))
        )*/
        return (<>
            <div>
                <h2><strong>KLAUZULA INFORMACYJNA – ZGODA NA PRZETWARZANIE DANYCH</strong></h2>
                <p>&nbsp;</p>
                <h3>Zgodnie z art. 13 ust. 1 i 2 rozporządzenia Parlamentu Europejskiego I Rady (UE) 2016/679 z dnia 27 kwietnia 2016 r. w sprawie ochrony osób fizycznych w związku z przetwarzaniem danych osobowych i w sprawie swobodnego przepływu takich danych oraz uchylenia dyrektywy 95/46/WE (ogólne rozporządzenie o ochronie danych), (Dz. U. UE. L Nr 119, str. 1) – dalej „RODO” informuję, iż:</h3>
                <h3>Klient który przekazał nam swoje dane osobowe ma prawo dostępu do tych danych oraz prawo:</h3>
                <h3><strong>INFORMACJA O PRAWIE SPRZECIWU</strong><br />
                    Jeśli Pani/Pana dane osobowe są przetwarzane dla celów marketingu bezpośredniego ma Pani/Pan prawo wnieść w dowolnym momencie, bezpłatnie sprzeciw wobec tego przetwarzania pierwotnego lub dalszego – w tym profilowania, o ile jest ono powiązane z marketingiem bezpośrednim.</h3>
                <h3>Administratorem Pani/Pana danych osobowych jest WAR ZONE S.C., ul. Kolbuszowska 25/1, 53-404 Wrocław</h3>
                <h3>We wszystkich sprawach dotyczących przetwarzania danych osobowych przez Administratora oraz korzystania z praw związanych z przetwarzaniem danych osobowych można kontaktować się na adres e-mail: biuro@war-zone.com.pl, lub pisemnie na wyżej podany adres Administratora z dopiskiem „dane osobowe”.</h3>
                <h3><strong>§1.</strong> Pani/Pana dane osobowe będą przez nas przetwarzane w celu dla którego udzielona została zgoda i może być to:</h3>
                <h3>realizacja rezerwacji na strzelnicę / laser tag</h3>
                <h3>Przetwarzanie w powyższym zakresie odbywa się na podstawie udzielonej zgody (art. 6 ust. 1 pkt a) RODO), ponadto przekazane dane osobowe mogą być przetwarzane:</h3>
                <h3>ewentualnie w celu marketingu bezpośredniego produktów i usług własnych Administratora, przetwarzanie odbywa się na podstawie tzw. prawnie uzasadnionego interesu Administratora jakim jest prowadzenie marketingu bezpośredniego swoich usług i produktów (art. 6 ust. 1 pkt. f) RODO),<br />
                    świadczenia usług przewidzianych dla użytkowników kont zgodnie z Regulaminem, którego akceptacja równoznaczna jest z zawarciem umowy o świadczenie tychże usług. Przetwarzanie odbywa się w celu wykonania umowy (art. 6 ust. 1 pkt. b) RODO),<br />
                    ewentualnie w celu dochodzenia roszczeń związanych z zawartą umową i świadczonymi usługami. Przetwarzanie odbywa się na podstawie prawnie uzasadnionego interesu Administratora jakim jest możliwość dochodzenia roszczeń (art. 6 ust. 1 pkt. f) RODO),<br />
                    wykonania ciążących na Administratorze obowiązków prawnych. Przetwarzanie odbywa się na podstawie obowiązku prawnego (art. 6 ust. 1 pkt c) RODO)</h3>.<br />
                <h3><strong>§2.</strong> Przekazane nam dane osobowe mogą być udostępnione podmiotom przetwarzającym dane na polecenie Administratora, m.inn. świadczącym usługi informatyczne, kurierskie, przetwarzania płatności, windykacji, doręczania korespondencji pocztowej, usługi prawne i inne wyspecjalizowane usługi. Takie podmioty przetwarzają dane wyłącznie na podstawie umowy z Administratorem i zgodnie z naszymi poleceniami. Udostępniamy tylko te dane osobowe, które umożliwiają wyżej wskazanym podmiotom świadczenie przez nich usług. Pani/Pana dane mogę być też udostępnione osobom trzecim w celach marketingowych jeśli wyrazi Pani/Pan zgodę na określone cele marketingowe, dla których niezbędne jest udostępnienie danych. Dane osobowe mogą być także dostępne dla dostawcy usług hostingowych, w zakresie utrzymania stron internetowych i kampanii marketingowych wyłącznie jednak w związku z działalnością statutową prowadzoną przez Administratora. W żadnym przypadku podmiot dla którego dostępne będą dane osobowe użytkowników nie stanie się jednak administratorem powierzonych nam danych osobowych.</h3>
                <h3><strong>§3.</strong> Pani/Pana dane osobowe nie będą przekazywane do odbiorców znajdujących się w państwach poza Europejskim Obszarem Gospodarczym (kraje Unii Europejskiej oraz Islandia, Norwegia i Lichtenstein).</h3>
                <h3><strong>§4.</strong> Pani/Pana dane osobowe będą przechowywane do momentu przedawnienia roszczeń z tytułu umowy/ świadczenia usług lub do momentu wygaśnięcia obowiązku przechowywania danych wynikającego z przepisów prawa. Tam gdzie przetwarzamy dane osobowe w oparciu o usprawiedliwiony interes Administratora dane osobowe nie będą przetwarzane do określonego celu jeśli zgłosi Pani/Pan sprzeciw wobec takiego przetwarzania. Jeśli przetwarzamy dane w oparciu o Pani/Pana zgodę, dane osobowe będą przetwarzane do momentu jej wycofania. Po upływie tego okresu dane osobowe zostaną usunięte lub poddane anonimizacji tj. zostaną przetworzone w taki sposób aby nie było możliwe powiązanie ich z żadną osobą.</h3>
                <h3><strong>§5.</strong> Posiada Pani/Pan prawo żądania dostępu do swoich danych osobowych, otrzymania ich kopii, sprostowania (poprawiania), usunięcia lub ograniczenia przetwarzania. wniesienia sprzeciwu wobec takiego przetwarzania. Jeśli podstawą przetwarzania danych jest prawnie uzasadniony interes Administratora, może Pani/Pan wnieść sprzeciw wobec takiego przetwarzania, w szczególności wobec przetwarzania na potrzeby marketingu bezpośredniego, w tym profilowania i w celach analitycznych. Przysługuje Pani/Panu prawo do przenoszenia danych osobowych. W takiej sytuacji otrzyma Pani/Pan swoje dane osobowe w ustrukturyzowanym, powszechnie używanym formacie, nadającym się do odczytu maszynowego.</h3>
                <h3><strong>§6.</strong> Przysługuje Pani/Panu prawo do cofnięcia zgody w dowolnym momencie. Wycofanie zgody nie wpływa jednak na zgodność z prawem przetwarzania, którego dokonano na podstawie zgody przed jej wycofaniem. Oświadczenie o cofnięciu zgody na przetwarzanie danych osobowych należy przekazać na adres: WAR ZONE S.C, ul. Kolbuszowska 25/1, 53-404 Wrocław</h3>
                <h3><strong>§7.</strong> Podanie danych osobowych jest dobrowolne ale konieczne do świadczenia usług objętych udzieloną zgodą – bez ich podania nie jest możliwe świadczenie usług. Podanie danych w celach marketingowych jest dobrowolne. Podanie danych osobowych w zakresie mającym podstawę w zobowiązaniu umownym, w tym przede wszystkim w zakresie świadczenia usług dla użytkowników kont jest dobrowolne, jednakże jest warunkiem zawarcia i wykonywania umowy. Konsekwencja niepodania danych będzie niemożność świadczenia usług przeznaczonych dla użytkowników kont. Podanie danych osobowych w zakresie wynikającym z przepisów prawa jest obowiązkowe i niezbędne do świadczenia przez Administratora usług/wykonania umowy.</h3>
                <h3><strong>§8.</strong> Przysługuje Pani/Panu prawo do wniesienia skargi do Prezesa Urzędu Ochrony Danych Osobowych, gdy uzna Pani/Pan, iż przetwarzanie Pani/ Pana danych osobowych narusza przepisy o ochronie danych osobowych,</h3>
                <h3><strong>§9.</strong> Pani/Pana dane będą przetwarzane w sposób zautomatyzowany ( w tym w formie profilowania) jednakże nie będzie to wywoływać wobec Pani/Pana żadnych skutków prawnych lub w podobny sposób istotnie wpływać na Pani/Pana sytuację. Profilowanie danych osobowych polega na przetwarzaniu Pani/Pana danych (również w sposób zautomatyzowany) poprzez wykorzystanie ich do oceny niektórych informacji, w szczególności do analizy lub prognozy osobistych preferencji oraz zainteresowań oraz przesyłania Pani/Panu ofert dotyczących zakupu towarów. Ma Pani/Pan prawo wnieść sprzeciw wobec profilowania.<br />
                </h3>
            </div>
        </>)
    }

    return (<>
        <Modal
            width="75vw"
            visible={props.modalVisible}
            onCancel={() => props.setModalVisible(false)}
            footer={null}>
            {DisplayRegulations()}
        </Modal>
    </>);
}
export default GdprContentModal;